<?php

/**
 * Class ilOneDriveSettingsGUI
 *
 * @author            Fabian Schmid <fs@studer-raimann.ch>
 * @version           1.0.0
 *
 * @ilCtrl_IsCalledBy ilOneDriveSettingsGUI : ilObjCloudGUI
 * @ingroup           ModulesCloud
 */
class ilOneDriveSettingsGUI extends ilCloudPluginSettingsGUI {

	/**
	 * @var ilPropertyFormGUI
	 */
	protected $form;


	protected function initPluginSettings() {
		$n = new ilNonEditableValueGUI($this->getPluginHookObject()->txt('token_expires'));
		$n->setValue(date(DATE_ISO8601, $this->getPluginObject()->getValidThrough()));
		$this->form->addItem($n);

		$n = new ilNonEditableValueGUI($this->getPluginHookObject()->txt('access_token'));
		$n->setValue($this->getPluginObject()->getAccessToken());
//		$this->form->addItem($n);

		$n = new ilNonEditableValueGUI($this->getPluginHookObject()->txt('refresh_token'));
		$n->setValue($this->getPluginObject()->getRefreshToken());
//		$this->form->addItem($n);
	}


	/**
	 * @return ilOneDrive
	 */
	public function getPluginObject() {
		return parent::getPluginObject(); // TODO: Change the autogenerated stub
	}
}

?>
