<?php
require_once('./Modules/Cloud/classes/class.ilCloudHookPlugin.php');
require_once('class.ilDynamicLanguage.php');
require_once('./Customizing/global/plugins/Modules/Cloud/CloudHook/OneDrive/classes/class.exodConfig.php');
require_once('./Customizing/global/plugins/Modules/Cloud/CloudHook/OneDrive/classes/App/class.exodAppBusiness.php');
require_once('./Customizing/global/plugins/Modules/Cloud/CloudHook/OneDrive/classes/App/class.exodAppPublic.php');

/**
 * Class ilOneDrivePlugin
 *
 * @author  Fabian Schmid <fs@studer-raimann.ch>
 * @version 1.0.0
 */
class ilOneDrivePlugin extends ilCloudHookPlugin implements ilDynamicLanguageInterfaceOD {

	const PLUGIN_NAME = 'OneDrive';
	/**
	 * @var exodAppBusiness
	 */
	protected static $app_instance;


	/**
	 * @return string
	 */
	public function getPluginName() {
		return self::PLUGIN_NAME;
	}

	//
	//	/**
	//	 * @param $a_var
	//	 *
	//	 * @return string
	//	 */
	//	public function txt($a_var) {
	//		return ilDynamicLanguageOD::getInstance($this, ilDynamicLanguageOD::MODE_DEV)->txt($a_var);
	//
	//		return parent::txt($a_var); // TODO: Change the autogenerated stub
	//	}

	/**
	 * @param exodBearerToken $exodBearerToken
	 *
	 * @return exodAppBusiness
	 */
	public function getExodApp(exodBearerToken $exodBearerToken) {
		$exodConfig = new exodConfig();
		$exodConfig->checkComplete();

		exodCurl::setSslVersion($exodConfig->getSSLVersion());
		exodCurl::setIpV4($exodConfig->getResolveIpV4());

		if ($exodConfig->getClientType() == exodApp::TYPE_BUSINESS) {
			$exodTenant = new exodTenant();
			$exodTenant->setTenantId($exodConfig->getTentantId());
			$exodTenant->setTenantName($exodConfig->getTenantName());

			$app = exodAppBusiness::getInstance($exodBearerToken, $exodConfig->getClientId(), $exodConfig->getClientSecret(), $exodTenant);
			$app->setIpResolveV4($exodConfig->getResolveIpV4());
		} elseif ($exodConfig->getClientType() == exodApp::TYPE_PUBLIC) {
			$app = exodAppPublic::getInstance($exodBearerToken, $exodConfig->getClientId(), $exodConfig->getClientSecret());
			$app->setIpResolveV4($exodConfig->getResolveIpV4());
		}

		//		$exodAppBusiness->setSslVersion(4);

		return $app;
	}


	/**
	 * @var ilOneDrivePlugin
	 */
	protected static $instance;


	/**
	 * @return ilOneDrivePlugin
	 */
	public static function getInstance() {
		if (! isset(self::$instance)) {
			self::$instance = new self();
		}

		return self::$instance;
	}


	/**
	 * @return string
	 */
	public function getCsvPath() {
		return './Customizing/global/plugins/Modules/Cloud/CloudHook/OneDrive/lang/lang.csv';
	}


	/**
	 * @return string
	 */
	public function getAjaxLink() {
		return NULL;
	}
}

?>
